### ISSUE TITLE
pgrep: `--terminal` doesn't support `?` as value

### ISSUE THREAD

**Issue by cakebaker** [uutils/procps#136]
`pgrep` from procps-ng supports `?` as a value for `--terminal` to match processes that do not have a controlling terminal. Our implementation doesn't support this value.
```
$ pgrep --terminal=? konsole
1265
1599
1640
1681
1741

$ cargo run pgrep --terminal=? konsole
// no output
```

**Comment by Krysztal112233** [comment]
Uh-huh. Looks like this one is a TerminalType flaw, I'll implement it later.
